name: CI python

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop
    
jobs:
    linting_flake:
        name: linting python
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Set up Python 3.12.2
              uses: actions/setup-python@v5
              with:
                python-version: "3.12.2"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
            - name: Lint with flake8
              run: |
                flake8 . --count --show-source --statistics --max-complexity=15 --exclude=*/__init__.py --ignore E501,E226,E402 
    tesing:
      name: testing python
      needs: linting_flake
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4.1.1
          - name: Set up Python 3.12.2
            uses: actions/setup-python@v5
            with:
              python-version: "3.12.2"
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
          - name: Test with pytest
            run: |
              pytest -m "not slow" --tb=no
