name: PyTorch Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U pytest
          pip install pylint 
      - name: Run tests
        run: |
          python -m unittest discover tests/
          pylint **/*.py
      - name: Create issue on Pylint failure
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TDDD96_GITHUB_TOKEN }}
          script: |
            const title = "Pylint Error in Workflow: ${{ github.workflow }}";
            const body = "Pylint detected an error in the code. Please investigate and fix it.";
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue = await github.issues.create({
              owner,
              repo,
              title,
              body,
            });
            console.log(`Created issue: ${issue.data.html_url}`);
