name: Super Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v4.1.1
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Super-linter
        uses: super-linter/super-linter@v6.1.1  # x-release-please-version
        env:
          VALIDATE_CHECKOV: false
          GITHUB_TOKEN: ${{ secrets.TDDD96_GITHUB_TOKEN }}
